---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mongodb-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mongo
    template:
      metadata:
        labels:
          app: mongo
      spec:
        volumes:
          - name: mongodb-storage
            persistentVolumeClaim:
              claimName: mongodb-volume-claim
        containers:
          - name: mongo
            image: mongo:latest
            ports:
              - containerPort: 27017
            volumeMounts:
              - mountPath: /data/db
                name: mongodb-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
  apiVersion: v1
  kind: Service
  metadata:
    name: mongodb-service
  spec:
    ports:
    - port: 27017
      targetPort: 27017
    selector:
      app: mongo
    type: ClusterIP
